name: Shop
version: 2.1.0
description: Create and manage shops.
author: Conjurate
main: conj.Shop.base.Initiate
softdepend: [PlaceholderAPI, Citizens]
api-version: 1.13
depend: [Vault]
commands:
  shop:
    description: Shop's main command.
    aliases: cshop

permissions:
  shop.worth.*:
    description: Gives access to all Shop worth commands
    children:
      shop.worth.set: true
      shop.worth.list: true
      shop.worth.item: true
  shop.citizen.*:
    description: Gives access to all Shop citizens commands
    children:
      shop.citizen.page: true
      shop.citizen.permission.add: true
      shop.citizen.permission.remove: true
      shop.citizen.permission.clear: true
  shop.page.*:
    description: Gives access to all Shop page commands
    children:
      shop.page.create: true
      shop.page.delete: true
      shop.page.manage: true
      shop.page.edit: true
      shop.page.size: true
      shop.page.copy: true
      shop.page.title: true
      shop.page.clear: true
      shop.page.list: true
      shop.page.open: true
      shop.page.type: true
      shop.page.recover: true
      shop.page.properties: true
  shop.blacklist.*:
    description: Gives access to all Shop blacklist commands
    children:
      shop.blacklist.add: true
      shop.blacklist.remove: true
      shop.blacklist.list: true
  shop.*:
    description: Gives access to all Shop commands
    children:
      shop.blacklist.*: true
      shop.page.*: true
      shop.worth.*: true
      shop.citizen.*: true
      shop.use: true
      shop.sign.break: true
      shop.sign.create: true
      shop.console: true
      shop.save: true
      shop.backup: true
      shop.reload: true
      shop.debug: true
      shop.tools: true